package DCRS;

/**
* DCRS/computeTaskInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/eclipse_workspace/Assignment2/src/DCRS.idl
* Tuesday, October 23, 2018 8:45:11 o'clock PM EDT
*/

public final class computeTaskInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public DCRS.computeTaskInterface value = null;

  public computeTaskInterfaceHolder ()
  {
  }

  public computeTaskInterfaceHolder (DCRS.computeTaskInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DCRS.computeTaskInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DCRS.computeTaskInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DCRS.computeTaskInterfaceHelper.type ();
  }

}
