package DCRS;


/**
* DCRS/computeTaskInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/eclipse_workspace/Assignment2/src/DCRS.idl
* Tuesday, October 23, 2018 8:45:11 o'clock PM EDT
*/

public abstract class computeTaskInterfacePOA extends org.omg.PortableServer.Servant
 implements DCRS.computeTaskInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("swapCourse", new java.lang.Integer (0));
    _methods.put ("addCourse", new java.lang.Integer (1));
    _methods.put ("removeCourse", new java.lang.Integer (2));
    _methods.put ("listCourseAvailability", new java.lang.Integer (3));
    _methods.put ("enrollCourse", new java.lang.Integer (4));
    _methods.put ("getClassSchedule", new java.lang.Integer (5));
    _methods.put ("dropCourse", new java.lang.Integer (6));
    _methods.put ("check", new java.lang.Integer (7));
    _methods.put ("setClient", new java.lang.Integer (8));
    _methods.put ("getClient", new java.lang.Integer (9));
    _methods.put ("setCapacity", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DCRS/computeTaskInterface/swapCourse
       {
         String studentID = in.read_string ();
         String newCourseID = in.read_string ();
         String oldCourseID = in.read_string ();
         String $result = null;
         $result = this.swapCourse (studentID, newCourseID, oldCourseID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DCRS/computeTaskInterface/addCourse
       {
         String courseID = in.read_string ();
         String sem = in.read_string ();
         String $result = null;
         $result = this.addCourse (courseID, sem);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DCRS/computeTaskInterface/removeCourse
       {
         String courseID = in.read_string ();
         String sem = in.read_string ();
         String $result = null;
         $result = this.removeCourse (courseID, sem);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DCRS/computeTaskInterface/listCourseAvailability
       {
         String sem = in.read_string ();
         String $result = null;
         $result = this.listCourseAvailability (sem);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DCRS/computeTaskInterface/enrollCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String sem = in.read_string ();
         String $result = null;
         $result = this.enrollCourse (studentID, courseID, sem);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DCRS/computeTaskInterface/getClassSchedule
       {
         String studentID = in.read_string ();
         String $result = null;
         $result = this.getClassSchedule (studentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DCRS/computeTaskInterface/dropCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String $result = null;
         $result = this.dropCourse (studentID, courseID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DCRS/computeTaskInterface/check
       {
         String id = in.read_string ();
         char c = in.read_char ();
         String $result = null;
         $result = this.check (id, c);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // DCRS/computeTaskInterface/setClient
       {
         String id = in.read_string ();
         this.setClient (id);
         out = $rh.createReply();
         break;
       }

       case 9:  // DCRS/computeTaskInterface/getClient
       {
         String $result = null;
         $result = this.getClient ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // DCRS/computeTaskInterface/setCapacity
       {
         int i = in.read_long ();
         this.setCapacity (i);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DCRS/computeTaskInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public computeTaskInterface _this() 
  {
    return computeTaskInterfaceHelper.narrow(
    super._this_object());
  }

  public computeTaskInterface _this(org.omg.CORBA.ORB orb) 
  {
    return computeTaskInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class computeTaskInterfacePOA
