package DCRS;


/**
* DCRS/computeTaskInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/eclipse_workspace/Assignment2/src/DCRS.idl
* Tuesday, October 23, 2018 8:45:11 o'clock PM EDT
*/

abstract public class computeTaskInterfaceHelper
{
  private static String  _id = "IDL:DCRS/computeTaskInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, DCRS.computeTaskInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DCRS.computeTaskInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DCRS.computeTaskInterfaceHelper.id (), "computeTaskInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DCRS.computeTaskInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_computeTaskInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DCRS.computeTaskInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DCRS.computeTaskInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DCRS.computeTaskInterface)
      return (DCRS.computeTaskInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DCRS._computeTaskInterfaceStub stub = new DCRS._computeTaskInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DCRS.computeTaskInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DCRS.computeTaskInterface)
      return (DCRS.computeTaskInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DCRS._computeTaskInterfaceStub stub = new DCRS._computeTaskInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
