package DCRS;


/**
* DCRS/computeTaskInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/eclipse_workspace/Assignment2/src/DCRS.idl
* Tuesday, October 23, 2018 8:45:11 o'clock PM EDT
*/

public interface computeTaskInterfaceOperations 
{
  String swapCourse (String studentID, String newCourseID, String oldCourseID);
  String addCourse (String courseID, String sem);
  String removeCourse (String courseID, String sem);
  String listCourseAvailability (String sem);
  String enrollCourse (String studentID, String courseID, String sem);
  String getClassSchedule (String studentID);
  String dropCourse (String studentID, String courseID);
  String check (String id, char c);
  void setClient (String id);
  String getClient ();
  void setCapacity (int i);
} // interface computeTaskInterfaceOperations
